@url = http://localhost:5353/1qz2x3c4v5b6n7m8l9k0j/auth
@random = {{$randomInt 1 9999999}}

### Signup user
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
    "firstName" : "name4",
    "lastName" : "lastName4",
    "userName" : "userNamse4",
    "email" : "userasd4@mail.com",
    "password" : "P4ssword.",
    "birthday" : "2000-09-27"
}

### Signin user
# @name signin
POST {{url}}/signin HTTP/1.1
Content-Type: application/json

{
    "email" : "",
    "userName" : "userName3",
    "password" : "P4ssword."
}

### Signout user
POST {{url}}/signout HTTP/1.1
Authorization: RefreshToken {{signin.response.body.RefreshToken}}

### Refresh token
# @name refreshToken
POST {{url}}/refresh-token HTTP/1.1
Authorization: RefreshToken {{signin.response.body.RefreshToken}}