@url = http://localhost:5353/1qz2x3c4v5b6n7m8l9k0j/categories
@value = 6

### Signin user
# @name signin
POST http://localhost:5353/1qz2x3c4v5b6n7m8l9k0j/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email" : "",
    "userName" : "userName2",
    "password" : "P4ssword."
}

### Get all categories
# @name get-categories
GET {{url}} HTTP/1.1
Authorization: Bearer {{signin.response.body.AccessToken}}

### new category
# @name new-category
POST {{url}} HTTP/1.1
Authorization: Bearer {{signin.response.body.AccessToken}}
Content-Type: application/json

{
    "name" : "Category {{value}}",
    "description" : "Category {{value}} description"
}